apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-cards
  annotations:
    meta.crossplane.io/maintainer: Bogdan Muțiu <bmutziu@bmutziu.me>
    meta.crossplane.io/source: github.com/bmutziu/provider-cards
    meta.crossplane.io/description: |
      A provider for playing cards from A Tour of Crossplane at bmutziu.me.
spec:
  controller:
    image: docker.io/bmutziu/provider-cards-controller-arm64:master
